# activiti 数据源
spring:
  datasource:
    druid:
      activiti:
        # 使用阿里的Druid连接池
        type: com.alibaba.druid.pool.DruidDataSource
        # JDBC 配置
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://101.132.136.225:3306/activiti_core?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
        # url换为jdbc-url 解决jdbcUrl is required with driverClassName错误
        jdbc-url: ${spring.datasource.activiti.url}
        username: root
        password: root@123

  # 参考配置 https://www.cnblogs.com/liaojie970/p/8857710.html
  activiti:
    # 数据源指定
    database-schema: ACTIVITI
    # 建表规则： 服务启动时检查数据库表，不存在则创建
    database-schema-update: true
    # 表示哪种情况下使用历史表，这里配置为all表示全部记录历史，方便绘制流程图; 记录历史等级 可配置的历史级别有none, acitivity, audit, full
    history-level: full
    # 表示使用历史表，如果不配置，则工程启动后可以检查数据库
    db-history-used: true
    # spring jpa使用
    jpa-enabled: false

  # jta 配置
  jta:
    atomikos:
      datasource:
        max-pool-size: 20
        borrow-connection-timeout: 60
      connectionfactory:
        max-pool-size: 20
        borrow-connection-timeout: 60